version: '3.7'

services:
    freevpn:
        image: freevpn:latest
        container_name: freevpn
        ports:
          - "443:443"
        volumes:
           - $PWD/db/:/etc/x-ui/
           - "./myssl:/etc/myssl"
        environment:
           - DOMAIN_NAME=
        restart: always
        logging:
          driver: "json-file"
          options:
            max-size: "1k"
            max-file: "1"

